### ISSUE TITLE
Rename MSlist and MSlist2

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#10]
IHMO `MSlist` and `MSlist2` are bad function names. Just from reading the names I had no idea what the functions are doing. Even after reading the man page it is hard to remember that `MSlist` creates `MassSpectrum` and `MSlist2` `MassPeaks` objects. Currently I have no good idea for a better name but maybe something like `matrixToSpectra`/`matrixToPeaks` ...

**Comment by Japal** [comment]
I agree, they have been re-named rawToSpectra and rawToPeaks
