### ISSUE TITLE
Use your own functions

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#11]
Is there a specific reason why you don't use your `MSlist` from `MSlist.R` in `importSpectra` but rewrite/copy&paste the code into the function?

**Comment by sgibb** [comment]
Use your `countPeaks` instead of
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L8
https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/summarySpectra.R#L8

**Comment by Japal** [comment]
Fixed. The function countPeaks only works on MassSpectra object. In any case, I have created and internal function to compute stats for MassSpectra and MassPeaks following #19.
