### ISSUE TITLE
Don't directly access the slots of MALDIquant objects but use their accessors

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#12]
It is good practice to use the accessor methods instead of the slots of a class. See for example: https://stackoverflow.com/questions/9900134/is-it-bad-practice-to-access-s4-objects-slots-directly-using and especially Martin Morgan's answer: https://stackoverflow.com/a/9900822

Beside being good practice it avoids errors (because the accessors add some additional checks), e.g.:
```r
library("MALDIquant")

s <- createMassSpectrum(mass=1:5, intensity=1:5)

## won't work, checks for equal length
intensity(s) <- 1:10
# Error in `intensity<-`(`*tmp*`, value = 1:10) :
#  Lengths of intensity(5) and value (10) have to be equal.

## works, no additional checks
s@intensity <- 1:10

## but now the object is broken
validObject(s)
# Error in validObject(s) :
#  invalid class “MassSpectrum” object: Lengths of mass (5) and intensity (10) have to be equal.
```

So use `mass(x)`, `intensity(x)`, `snr(x)` and `metaData(x)` instead of `x@mass`, `x@intensity`, `x@metaData`, and `x@snr` wherever possible (the would be some edge cases where you have to access the slots directly).

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/addMetadata.R#L4

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L12

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L13

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L16

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L17

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/snrPeaks.R#L7

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L8

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L9

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L10             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L11             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L12             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L13             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L14             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L15             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L16             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L17             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L18             
                                                                                                                  
https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L19

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L20

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L21

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summaryPeaks.R#L22

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L8

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L9

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L10

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L11

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L12

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L13

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L14

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L15

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summarySpectra.R#L16

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/transfIntensity.R#L14

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/transfIntensity.R#L15

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/transfIntensity.R#L18

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/transfIntensity.R#L19

**Comment by Japal** [comment]
Done, thanks for the pointer.
