### ISSUE TITLE
Use `isMassSpectrumList`

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#13]
There are still some pieces of code that could use `isMassSpectrumList`:

https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/redResolution.R#L3-L7

https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/transfIntensity.R#L3-L7

Obviously I don't catch all with #1 .

**Comment by Japal** [comment]
Sorry I missed that. All revised now.
