### ISSUE TITLE
Functions from mvoutlier

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#14]
Why you copy&paste `mvoutlier::arw` and not just depend on the package and use the function from it?
https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/detectOutliers.R#L22-L58

(using your own version of code forces you to look for bugs and updates yourself)

**Comment by Japal** [comment]
Being this a small function which is easy to maintain, we prefer to have our own copy included in MALDIrppa and do not depend on mvoutlier updates.
