### ISSUE TITLE
Don't calculate summary statistics (median etc.) twice

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#15]
Instead of calculating `quantile`, `mean`, `median` etc. twice to get each limit use temporary variables or vectorisation:
```r
lim <- mean(est, na.rm=TRUE) + sd(est, na.rm=TRUE) + c(threshold, -threshold)
```
https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/screenSpectra.R#L79-L98

**Comment by Japal** [comment]
Vectorised.
