### ISSUE TITLE
transformIntensity vs transfIntensity

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#17]
While I totally understand why you create `tranfIntensity` I don't understand why you use
```r
spectra <- transfIntensity(spectra, fun = function(x) sqrt(x))
```
instead of
```r
spectra <- transformIntensity(spectra, "sqrt")
```
in the vignette?

In earlier versions of `MALDIquant` there was a `fun` argument in `transformIntensity` that accepted user-defined functions. We removed it because many users of `MALDIquant` don't understand the concept of anonymous functions like `function(x)sqrt(x)` (BTW: `transfIntensity(spectra, fun=sqrt)` should be sufficient here). Maybe it was not the best decision we made.

**Comment by Japal** [comment]
Yes, it was unnecessary to be that explicit. The possibility of using user-defined functions is now stressed in the vignette and revised help documentation. As you say, this simply recovers an old functionality of transformIntensity that I missed.

**Comment by sgibb** [comment]
Ok, fine. Sry, for removing this functionality from `MALDIquant` but I discussed it with my supervisor and we won't readd it for now.
