### ISSUE TITLE
Simplify `redResolution`

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#18]
As mentioned in #4 `MALDIquant` offers the `[` for `MassSpectrum` and `MassPeaks` objects. So the following code in `redResolution` could be simplified:
https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/redResolution.R#L10-L18

```r
if (is.list(x)) {
   x <- lapply(x, function(xx)xx[seq(1, length(xx), by=by)])
} else
   x <- x[seq(1, length(xx), by=by)]
}

**Comment by Japal** [comment]
Updated, thanks!
