### ISSUE TITLE
Use an internal function for summary in `summarySpectra` and `summaryPeaks`

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#19]
`summarySpectra` and `summaryPeaks` are nearly identical. I would suggest to create an internal function that calculates the summary statistics for `mass` and `intensity`. This could be used in `summarySpectra` and `summaryPeaks`. The `snr` statistics could be easily `cbind`ed to the `out` `data.frame`.

**Comment by Japal** [comment]
The common stats are now computed in an internal function (.summaryStats) and syntax has been simplified.
