### ISSUE TITLE
Write unit tests for the most critical functions.

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#3]
You use the package `testthat` in your `DESCRIPTION` file but doesn't create any unit test. 
In my opinion it is very important for a scientific package to provide unit tests to ensure that all functions do what they are supposed to do.

**Comment by Japal** [comment]
Yes, thanks for your suggestion. I have included some unit tests for the main functions

**Comment by sgibb** [comment]
Great! (but the test suite could be extended 😉)
