### ISSUE TITLE
Remove `==TRUE` and `==FALSE` in `if` statements

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#5]
`if (x==TRUE)` is superfluous. `if` expects a condition to be `TRUE` or `FALSE`, that means `if(x)` is enough if `x` is `logical` (or `numeric`). Your current approach is evaluated twice. First `x` is compared to `TRUE` and secondly the `if` tests whether this result is `TRUE`.

Instead of `if (x==FALSE)` just use `if (!x)`.

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L16

Use `if (binary)` here.

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L103

Use `if (!binary)` here.

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L104

Other lines with the same approach:

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L107

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/peakPatterns.R#L12

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/peakPatterns.R#L30

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/peakPatterns.R#L34

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/plot.scSpectra.R#L5

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/plot.scSpectra.R#L8

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/plot.scSpectra.R#L14

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L5

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/screenSpectra.R#L23

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/screenSpectra.R#L26

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summary.scSpectra.R#L3

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/summary.scSpectra.R#L7

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/transfIntensity.R#L5

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/writeIntensity.R#L225

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/writeIntensity.R#L226

**Comment by sgibb** [comment]
Not only in `if` statements but everywhere, e.g.

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L104

`int[is.na(int)] <- 0` would be enough.

**Comment by Japal** [comment]
All changed.
