### ISSUE TITLE
Use `&&` and `||` in `if` instead of `&` and `|`

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#6]
`&&` is different from `&`, see `?"&&"`:

> ‘&’ and ‘&&’ indicate logical AND and ‘|’ and ‘||’ indicate
logical OR.  The shorter form performs elementwise comparisons in
much the same way as arithmetic operators.  The longer form
evaluates left to right examining only the first element of each
vector.  Evaluation proceeds only until the result is determined.
The longer form is appropriate for programming control-flow and
typically preferred in ‘if’ clauses.

Lines:

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L6

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/detectOutliers.R#L11

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/peakPatterns.R#L41

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L3

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/redResolution.R#L8

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/screenSpectra.R#L13

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/screenSpectra.R#L18

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/transfIntensity.R#L3

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/writeIntensity.R#L3

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/writeIntensity.R#L225

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/writeIntensity.R#L226

**Comment by Japal** [comment]
Done
