### ISSUE TITLE
Don't use nested function definitions

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#7]
Dear Javier,

please don't use nested function definitions. While it is valid R code it is generally considered as bad practice. Because the nested (private) functions life in the namespace/frame of the parent functions they are hard to debug, hard to test (unit tests) and could not be reused by other functions.

An example (functions nested in 2 levels):

https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/detectOutliers.R#L1-L22

Instead of hiding the functions inside another function you could hide your private functions by not exporting them in the `NAMESPACE` file.

**Comment by Japal** [comment]
Nested functions of substantial size and relevance are now defined as separate functions for internal use only and not exported.
