### ISSUE TITLE
Question regarding `importSpectra`

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#8]
Do you know `MALDIquantForeign::importCsv`? Do you want to avoid to depend on `MALDIquantForeign` or are there any other reasons why you do not can/want to use `MALDIquantForeign::importCsv`?

**Comment by Japal** [comment]
I knew about MALDIquantForeign, but I was not aware of importCsv. Certainly it offers the same functionality. I think that the reason why I implemented importSpectra was that MALDIquantForeign was not still on the CRAN, and importCsv might not be included, by that time. In any case, I'd rather keep importSpectra in MALDIrppa for completeness and include reference to MALDIquantForeign in the help system and the vignette for the case that importing from more sophisticated format files is required.

**Comment by sgibb** [comment]
Ok, I am fine with that decision. `MALDIquantForeign` would add some more dependencies (e.g. `XML`, `RNetCDF`) to your package. If you just need the csv import it is ok to provide your own function.
