### ISSUE TITLE
Pre-allocate memory

### ISSUE THREAD

**Issue by sgibb** [Japal/MALDIrppa#9]
As I already described in #4.

Here are some examples that could be improved by pre-allocating memory:

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/importSpectra.R#L5-L8

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/MSlist2.R#L3-L6

https://github.com/Japal/MALDIrppa/blob/39adb988f59d7cba5d9dcb4270174cce44a7e1d1/R/MSlist.R#L3-L6

Already addressed by #4 :
https://github.com/Japal/MALDIrppa/blob/82cc2630f189af56ffd26480506873197f19e36e/R/deletePeaks.R#L10-L19

**Comment by Japal** [comment]
Done
